### ISSUE TITLE
Cant install the app ....

### ISSUE THREAD

**Issue by michaelassa01** [gbozee/django-ravepay#7]

**Comment by PetrJoe** [comment]
I tried installing ravepay but keep getting this error. But my virtualenv is activated

 WARNING: Generating metadata for package ravepay produced metadata for project name django-ravepay. Fix your #egg=ravepay fragments.
Discarding git+https://github.com/gbozee/django-ravepay.git@master#egg=ravepay: Requested django-ravepay from git+https://github.com/gbozee/django-ravepay.git@master#egg=ravepay has inconsistent name: filename has 'ravepay', but metadata has 'django-ravepay'
ERROR: Could not find a version that satisfies the requirement ravepay (unavailable) (from versions: none)
ERROR: No matching distribution found for ravepay (unavailable)
